# -*- coding: utf-8 -*-
"""Microgrid (Auction)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bY9NSSPfibV70Dc5earDXa66pM57cSvq
"""



"""Let's define the components of your microgrid based on your input:

*   **Generation:** Wind turbine, PV (solar), Diesel generator, Energy storage (battery), Main grid connection.
*   **Customer Load:** Aggregate energy consumption of all customers.

Now, let's start creating simple models for each of these components. These models will define how each component interacts within the simulation.
"""

class MicrogridComponent:
    """Base class for all microgrid components."""
    def __init__(self, name):
        self.name = name
        self.power_output = 0  # Represents power output (positive) or consumption (negative)

    def update(self, timestep, data=None):
        """
        Update the component's state and power output based on the current timestep and data.
        This method should be implemented by subclasses.
        """
        raise NotImplementedError("Subclasses must implement the update method")

    def get_power_output(self):
        """Get the current power output of the component."""
        return self.power_output

    def __str__(self):
        return f"{self.name}: {self.power_output:.2f} kW"

"""Now, let's create classes for each of the specific microgrid components you've identified, inheriting from the `MicrogridComponent` base class. Each of these classes will need an `update` method that simulates its behavior over time."""

class WindTurbine(MicrogridComponent):
    """Represents a wind turbine."""
    def __init__(self, name, capacity):
        super().__init__(name)
        self.capacity = capacity  # Maximum power output in kW

    def update(self, timestep, data=None):
        """
        Update the wind turbine's power output based on wind speed data.

        Args:
            timestep: The current simulation timestep.
            data: A dictionary containing relevant data, e.g., {'wind_speed': float}.
        """
        if data and 'wind_speed' in data:
            wind_speed = data['wind_speed']
            # Simple wind power model (can be replaced with a more complex one)
            # Assuming a cut-in speed, rated speed, and cut-out speed
            cut_in_speed = 3  # m/s
            rated_speed = 12  # m/s
            cut_out_speed = 25  # m/s

            if wind_speed < cut_in_speed or wind_speed > cut_out_speed:
                self.power_output = 0
            elif wind_speed >= rated_speed:
                self.power_output = self.capacity
            else:
                # Linear interpolation between cut-in and rated speed
                self.power_output = self.capacity * (wind_speed - cut_in_speed) / (rated_speed - cut_in_speed)
        else:
            self.power_output = 0 # No wind data, no output

class PVSystem(MicrogridComponent):
    """Represents a PV (solar) system."""
    def __init__(self, name, capacity):
        super().__init__(name)
        self.capacity = capacity  # Maximum power output in kW

    def update(self, timestep, data=None):
        """
        Update the PV system's power output based on solar irradiance data.

        Args:
            timestep: The current simulation timestep.
            data: A dictionary containing relevant data, e.g., {'solar_irradiance': float}.
        """
        if data and 'solar_irradiance' in data:
            solar_irradiance = data['solar_irradiance'] # Assuming data is in W/m^2
            # Simple PV power model (can be replaced with a more complex one)
            # Assuming a standard test condition (STC) irradiance of 1000 W/m^2
            stc_irradiance = 1000
            self.power_output = self.capacity * (solar_irradiance / stc_irradiance)
            # Ensure output does not exceed capacity
            if self.power_output > self.capacity:
                self.power_output = self.capacity
            # Ensure output is not negative
            if self.power_output < 0:
                self.power_output = 0
        else:
            self.power_output = 0 # No solar data, no output

class DieselGenerator(MicrogridComponent):
    """Represents a diesel generator."""
    def __init__(self, name, capacity, fuel_consumption_rate=0.2, generation_cost_per_kwh=0.3): # Added generation_cost_per_kwh
        super().__init__(name)
        self.capacity = capacity  # Maximum power output in kW
        self.fuel_consumption_rate = fuel_consumption_rate # Example: fuel consumed per kWh generated
        self.generation_cost_per_kwh = generation_cost_per_kwh # Cost to generate 1 kWh
        self.fuel_level = 1000 # Example: initial fuel level
        self.is_running = False

    def update(self, timestep, data=None):
        """
        Update the diesel generator's power output and fuel level.

        Args:
            timestep: The current simulation timestep (in hours).
            data: A dictionary containing relevant data, e.g., {'required_power': float}.
                  This could also include commands to start/stop the generator.
        """
        required_power = data.get('required_power', 0) if data else 0

        # Ensure diesel only runs if fuel is available and required_power is positive
        if required_power > 0 and self.fuel_level > 0:
            self.is_running = True
            # Generate power up to capacity or required power, whichever is less
            power_to_generate = min(self.capacity, required_power)

            # Check if enough fuel to generate power_to_generate for the timestep
            max_power_from_fuel_kwh = (self.fuel_level / self.fuel_consumption_rate) if self.fuel_consumption_rate > 0 else float('inf')
            max_power_from_fuel_for_timestep = max_power_from_fuel_kwh / timestep if timestep > 0 else float('inf')

            self.power_output = min(power_to_generate, max_power_from_fuel_for_timestep)

            # Calculate fuel consumption based on actual generated power and rate
            fuel_consumed = self.power_output * self.fuel_consumption_rate * timestep
            self.fuel_level -= fuel_consumed
            if self.fuel_level < 0: # Should not happen if max_power_from_fuel is calculated correctly, but as a safeguard
                self.fuel_level = 0
                self.power_output = 0 # Cannot generate if fuel runs out mid-timestep

        else:
            self.is_running = False
            self.power_output = 0

    def get_fuel_level(self):
        """Get the current fuel level."""
        return self.fuel_level

    def __str__(self):
        return f"{self.name}: {self.power_output:.2f} kW, Fuel: {self.fuel_level:.2f}"

"""Now that we have models for each component, let's integrate them into a main `Microgrid` simulation environment. This class will manage all the components and simulate their interactions over time."""

class Battery(MicrogridComponent):
    """Represents an energy storage system (battery)."""
    def __init__(self, name, capacity_kwh, max_charge_rate_kw, max_discharge_rate_kw, initial_soc=0.5,
                 charge_cost_per_kwh=0.05, discharge_cost_per_kwh=0.02): # Added costs
        super().__init__(name)
        self.capacity_kwh = capacity_kwh  # Total energy capacity in kWh
        self.max_charge_rate_kw = max_charge_rate_kw  # Maximum charging power in kW
        self.max_discharge_rate_kw = max_discharge_rate_kw  # Maximum discharging power in kW
        self.soc = initial_soc  # State of Charge (0.0 to 1.0)
        self.charge_cost_per_kwh = charge_cost_per_kwh # Cost to charge 1 kWh
        self.discharge_cost_per_kwh = discharge_cost_per_kwh # Cost of discharging 1 kWh (e.g., degradation)
        self.power_output = 0 # Power output (discharge is positive, charge is negative)

    def update(self, timestep, data=None):
        """
        Update the battery's state of charge and power output.

        Args:
            timestep: The current simulation timestep (in hours).
            data: A dictionary containing relevant data, e.g., {'charge_power': float} or {'discharge_power': float}.
                  Positive values for discharge, negative for charge.
        """
        requested_power = 0
        if data and 'discharge_power' in data and data['discharge_power'] > 0:
            requested_power = data['discharge_power'] # Positive for discharge
        elif data and 'charge_power' in data and data['charge_power'] > 0:
            requested_power = -data['charge_power'] # Negative for charge (charge_power is a positive value in data)

        if requested_power > 0: # Discharge
            # Limit requested discharge by max rate and available energy
            max_available_discharge_energy_kwh = self.soc * self.capacity_kwh
            max_discharge_power_possible = max_available_discharge_energy_kwh / timestep if timestep > 0 else float('inf')

            actual_power = min(requested_power, self.max_discharge_rate_kw, max_discharge_power_possible)

            energy_change_kwh = actual_power * timestep
            self.soc -= (energy_change_kwh / self.capacity_kwh)
            self.power_output = actual_power

        elif requested_power < 0: # Charge
            requested_charge_power = -requested_power # Convert to positive value for calculation
            # Limit requested charge by max rate and available capacity
            max_available_charge_energy_kwh = (1.0 - self.soc) * self.capacity_kwh
            max_charge_power_possible = max_available_charge_energy_kwh / timestep if timestep > 0 else float('inf')

            actual_power = min(requested_charge_power, self.max_charge_rate_kw, max_charge_power_possible)

            energy_change_kwh = actual_power * timestep
            self.soc += (energy_change_kwh / self.capacity_kwh)
            self.power_output = -actual_power # Charging is negative power output

        else:
            self.power_output = 0 # No charge/discharge command

        # Ensure SOC is within bounds after operations (should be handled by limits but good fallback)
        self.soc = max(0.0, min(1.0, self.soc))

    def get_soc(self):
        """Get the current state of charge (SOC)."""
        return self.soc

    def __str__(self):
        return f"{self.name}: {self.power_output:.2f} kW, SOC: {self.soc:.2f}"

class MainGrid(MicrogridComponent):
    """Represents the connection to the external power grid."""
    def __init__(self, name, import_limit=float('inf'), export_limit=float('inf'),
                 import_price_per_kwh=0.2, export_price_per_kwh=0.1): # Added prices
        super().__init__(name)
        self.import_limit = import_limit  # Maximum power that can be imported from the grid (kW)
        self.export_limit = export_limit  # Maximum power that can be exported to the grid (kW)
        self.import_price_per_kwh = import_price_per_kwh # Cost to import 1 kWh from grid
        self.export_price_per_kwh = export_price_per_kwh # Revenue from exporting 1 kWh to grid
        self.power_output = 0  # Power flow (positive for import, negative for export)

    def update(self, timestep, data=None):
        """
        Update the main grid's power flow.

        Args:
            timestep: The current simulation timestep.
            data: A dictionary containing relevant data, e.g., {'requested_power': float}.
                  Positive values for importing from the grid, negative for exporting.
        """
        requested_power = data.get('requested_power', 0) if data else 0

        if requested_power > 0:  # Requesting power from the grid (import)
            self.power_output = min(requested_power, self.import_limit)
        elif requested_power < 0:  # Sending power to the grid (export)
            self.power_output = max(requested_power, -self.export_limit) # export_limit is positive, so we need the negative
        else:
            self.power_output = 0 # No power exchange requested

    def __str__(self):
        # Display positive for import, negative for export
        flow_direction = "importing" if self.power_output > 0 else ("exporting" if self.power_output < 0 else "not exchanging")
        return f"{self.name}: {abs(self.power_output):.2f} kW ({flow_direction})"

class CustomerLoad(MicrogridComponent):
    """Represents the aggregate energy consumption of customers."""
    def __init__(self, name):
        super().__init__(name)
        self.power_output = 0  # Load is power consumption (negative in our convention)

    def update(self, timestep, data=None):
        """
        Update the customer load based on load data.

        Args:
            timestep: The current simulation timestep.
            data: A dictionary containing relevant data, e.g., {'load': float}.
                  Load should be a positive value representing consumption.
        """
        if data and 'load' in data:
            # Load is consumption, so it's negative power output
            self.power_output = -data['load']
        else:
            self.power_output = 0 # No load data, no consumption

    def __str__(self):
        # Display load as a positive value
        return f"{self.name}: {abs(self.power_output):.2f} kW (consumption)"

class Microgrid:
    """Represents the microgrid simulation environment."""
    def __init__(self, components):
        """
        Args:
            components: A dictionary of MicrogridComponent objects, e.g., {'wind': WindTurbine(...), 'battery': Battery(...), ...}.
        """
        self.components = components
        self.time = 0
        self.history = [] # To store simulation results

    def update(self, timestep, data):
        """
        Update the state of all components for the current timestep and manage power balance using economic dispatch.

        Args:
            timestep: The duration of the current timestep (in hours).
            data: A dictionary containing data for each component, e.g., {'wind': {'wind_speed': ...}, 'customer_load': {'load': ...}}.
        """
        current_state = {'time': self.time}
        total_generation_renewables = 0
        total_load_consumption = 0

        # Reset power_output for dispatchable components before new dispatch calculations
        # Renewables and load update first, their output directly determined by data
        for name, component in self.components.items():
            if name in ['diesel', 'battery', 'grid']:
                component.power_output = 0 # Clear previous dispatch output

        # Update renewable sources and load first
        for name, component in self.components.items():
            component_data = data.get(name, {})
            if name in ['wind', 'pv']: # Renewable sources
                 component.update(timestep, component_data)
                 current_state[name + '_power'] = component.get_power_output()
                 total_generation_renewables += component.get_power_output()
            elif name == 'load': # Load
                 component.update(timestep, component_data)
                 current_state[name + '_power'] = component.get_power_output()
                 total_load_consumption += component.get_power_output() # load_power is negative, so adding it increases the deficit

        net_power_balance_after_renewables_load = total_generation_renewables + total_load_consumption
        power_to_balance = -net_power_balance_after_renewables_load # Positive means deficit, negative means surplus

        # Components involved in balancing
        diesel = self.components.get('diesel')
        battery = self.components.get('battery')
        grid = self.components.get('grid')

        # --- Economic Dispatch / Simplified Auction Logic ---
        if power_to_balance > 0:  # Deficit - Need to supply power
            suppliers = []
            if diesel:
                max_diesel_power_available_kwh = (diesel.get_fuel_level() / diesel.fuel_consumption_rate) if diesel.fuel_consumption_rate > 0 else float('inf')
                max_diesel_power_available = min(diesel.capacity, max_diesel_power_available_kwh / timestep if timestep > 0 else float('inf'))
                if max_diesel_power_available > 0:
                    suppliers.append({'name': 'diesel', 'component': diesel, 'cost': diesel.generation_cost_per_kwh, 'max_supply': max_diesel_power_available})
            if battery:
                max_battery_discharge_power_kwh = battery.get_soc() * battery.capacity_kwh
                max_battery_discharge_power = min(battery.max_discharge_rate_kw, max_battery_discharge_power_kwh / timestep if timestep > 0 else float('inf'))
                if max_battery_discharge_power > 0:
                    suppliers.append({'name': 'battery_discharge', 'component': battery, 'cost': battery.discharge_cost_per_kwh, 'max_supply': max_battery_discharge_power})
            if grid:
                max_grid_import_power = grid.import_limit
                if max_grid_import_power > 0:
                    suppliers.append({'name': 'grid_import', 'component': grid, 'cost': grid.import_price_per_kwh, 'max_supply': max_grid_import_power})

            # Sort suppliers by cost (cheapest first)
            suppliers.sort(key=lambda x: x['cost'])

            for supplier in suppliers:
                if power_to_balance <= 0:
                    break

                # Determine how much power this supplier should try to provide
                power_to_provide_by_supplier = min(power_to_balance, supplier['max_supply'])

                # Update the component and get its actual power output
                if supplier['name'] == 'diesel':
                    supplier['component'].update(timestep, {'required_power': power_to_provide_by_supplier})
                elif supplier['name'] == 'battery_discharge':
                    supplier['component'].update(timestep, {'discharge_power': power_to_provide_by_supplier})
                elif supplier['name'] == 'grid_import':
                    supplier['component'].update(timestep, {'requested_power': power_to_provide_by_supplier}) # Positive for import

                actual_power_supplied = supplier['component'].get_power_output() # This is positive for supply
                power_to_balance -= actual_power_supplied

                # Store the updated power for this component
                if supplier['name'] == 'diesel':
                    current_state['diesel_power'] = actual_power_supplied
                elif supplier['name'] == 'battery_discharge':
                    current_state['battery_power'] = actual_power_supplied
                elif supplier['name'] == 'grid_import':
                    current_state['grid_power'] = actual_power_supplied

        elif power_to_balance < 0:  # Surplus - Need to absorb power
            consumers = []
            power_to_absorb = -power_to_balance # Convert to positive quantity for absorption

            if battery:
                max_battery_charge_power_kwh = (1.0 - battery.get_soc()) * battery.capacity_kwh
                max_battery_charge_power = min(battery.max_charge_rate_kw, max_battery_charge_power_kwh / timestep if timestep > 0 else float('inf'))
                if max_battery_charge_power > 0:
                    consumers.append({'name': 'battery_charge', 'component': battery, 'cost': battery.charge_cost_per_kwh, 'max_consume': max_battery_charge_power})
            if grid:
                max_grid_export_power = grid.export_limit
                if max_grid_export_power > 0:
                    # Exporting yields revenue, so its 'cost' for absorbing surplus is negative (profit)
                    consumers.append({'name': 'grid_export', 'component': grid, 'cost': -grid.export_price_per_kwh, 'max_consume': max_grid_export_power})

            # Sort consumers by cost (most "profitable" or least expensive to absorb first, i.e., lowest cost value)
            consumers.sort(key=lambda x: x['cost'])

            for consumer in consumers:
                if power_to_absorb <= 0:
                    break

                # Determine how much power this consumer should try to absorb
                power_to_send_to_consumer = min(power_to_absorb, consumer['max_consume'])

                # Update the component
                if consumer['name'] == 'battery_charge':
                    consumer['component'].update(timestep, {'charge_power': power_to_send_to_consumer})
                elif consumer['name'] == 'grid_export':
                    consumer['component'].update(timestep, {'requested_power': -power_to_send_to_consumer}) # Negative for export

                actual_power_absorbed = -consumer['component'].get_power_output() # get_power_output is negative for charge/export, so make it positive for absorption
                power_to_absorb -= actual_power_absorbed

                # Store the updated power for this component
                if consumer['name'] == 'battery_charge':
                    current_state['battery_power'] = consumer['component'].get_power_output()
                elif consumer['name'] == 'grid_export':
                    current_state['grid_power'] = consumer['component'].get_power_output()

            power_to_balance = -power_to_absorb # Convert back to original sign convention (remaining surplus is negative)

        # Ensure all components (including those not involved in dispatch decisions) have their power_output recorded
        for name, component in self.components.items():
            if name + '_power' not in current_state:
                 current_state[name + '_power'] = component.get_power_output()

        # Store battery SOC
        if battery:
            current_state['battery_soc'] = battery.get_soc()

        # The final net_power_balance reflects any remaining imbalance after dispatch
        current_state['net_power_balance'] = power_to_balance

        # Store the current state
        self.history.append(current_state)

        # Advance time
        self.time += timestep

    def run_simulation(self, timesteps, data_series):
        """
        Run the microgrid simulation for a specified number of timesteps.

        Args:
            timesteps: The total number of timesteps to simulate.
            data_series: A list of dictionaries, where each dictionary contains the data for a single timestep.
                         The length of this list should be equal to the number of timesteps.
        """
        self.history = [] # Reset history for a new simulation run
        self.time = 0 # Reset time

        # Initialize component states at time 0 before the first update
        initial_state = {'time': self.time}
        for name, component in self.components.items():
             initial_state[name + '_power'] = component.get_power_output() # Should be 0 initially for most
        initial_state['net_power_balance'] = 0 # Assuming initial state is balanced
        # Initialize battery SOC for time 0
        if 'battery' in self.components:
            initial_state['battery_soc'] = self.components['battery'].get_soc()
        self.history.append(initial_state)


        for i in range(timesteps):
            timestep_data = data_series[i]
            # Assuming each step represents 1 hour for now
            self.update(1, timestep_data)
            # print(f"Time: {self.time}h, Net Balance (after dispatch): {self.history[-1]['net_power_balance']:.2f} kW") # Commented out to reduce output

    def get_history(self):
        """Get the simulation history."""
        return self.history

    def __str__(self):
        return f"Microgrid with components: {', '.join(self.components.keys())}"

"""Now that we have the microgrid simulation environment, we need to define the **state space** and **action space** for reinforcement learning.

*   **State Space:** What information about the microgrid is available to the reinforcement learning agent at each timestep? This could include things like:
    *   Current power output of each generation source (wind, solar, diesel)
    *   Battery state of charge (SOC)
    *   Customer load
    *   Time of day/year (can influence renewable generation and load)
    *   Grid status/price (if connected to the main grid)

*   **Action Space:** What decisions can the reinforcement learning agent make at each timestep? This could include:
    *   Dispatching the diesel generator (on/off, power output level)
    *   Charging or discharging the battery (power level)
    *   Buying or selling power to the main grid (power level)

Let's think about what a suitable state and action space would be for your microgrid setup. We can start by defining these spaces based on the components you have included.
"""

# Create instances of the microgrid components
# Adjusted costs to ensure diesel participates in the auction process
wind_turbine = WindTurbine(name='WindTurbine', capacity=100)
pv_system = PVSystem(name='PVSystem', capacity=50)
diesel_generator = DieselGenerator(name='DieselGenerator', capacity=75, fuel_consumption_rate=0.2, generation_cost_per_kwh=0.08) # Decreased cost to make it competitive
battery = Battery(name='Battery', capacity_kwh=200, max_charge_rate_kw=50, max_discharge_rate_kw=50,
                 initial_soc=0.5, charge_cost_per_kwh=0.05, discharge_cost_per_kwh=0.15) # Increased discharge cost
main_grid = MainGrid(name='MainGrid', import_limit=100, export_limit=100,
                     import_price_per_kwh=0.25, export_price_per_kwh=0.1) # Increased import price
customer_load = CustomerLoad(name='CustomerLoad')

# Create a Microgrid instance with the components
components = {
    'wind': wind_turbine,
    'pv': pv_system,
    'diesel': diesel_generator,
    'battery': battery,
    'grid': main_grid,
    'load': customer_load
}
microgrid = Microgrid(components)

# Create some sample time-series data for a few timesteps
# This data would typically come from external sources or profiles
sample_data_series = [
    {'wind': {'wind_speed': 2}, 'pv': {'solar_irradiance': 50}, 'load': {'load': 100}}, # Timestep 1: Low renewables, high load -> DEFICIT. Diesel should run (cheapest supply).
    {'wind': {'wind_speed': 5}, 'pv': {'solar_irradiance': 100}, 'load': {'load': 150}}, # Timestep 2: Low wind and solar, high load (deficit - might need diesel/grid/battery discharge)
    {'wind': {'wind_speed': 10}, 'pv': {'solar_irradiance': 800}, 'load': {'load': 50}},  # Timestep 3: High renewables, low load -> SURPLUS. Battery charge or grid export.
    {'wind': {'wind_speed': 3}, 'pv': {'solar_irradiance': 0}, 'load': {'load': 120}}, # Timestep 4: Low wind, no solar (night), high load -> DEFICIT. Battery might be low, diesel should run.
    {'wind': {'wind_speed': 8}, 'pv': {'solar_irradiance': 600}, 'load': {'load': 70}},  # Timestep 5: Moderate wind and solar, moderate load -> BALANCE/SLIGHT SURPLUS.
]

# Run the simulation
timesteps_to_simulate = len(sample_data_series)
microgrid.run_simulation(timesteps_to_simulate, sample_data_series)

# Display the simulation history
display(microgrid.get_history())

import matplotlib.pyplot as plt

# Set the global font size for all matplotlib plots
plt.rcParams.update({'font.size': 16})

print("Global font size set to 16.")

import pandas as pd
import matplotlib.pyplot as plt

# Get the simulation history
history_data = microgrid.get_history()
history_df = pd.DataFrame(history_data)

# Filter out the initial state (first row where all power is 0) for plotting
plotting_df = history_df.iloc[1:].copy()

# Create a new column for simulation step numbers (1 to 5)
plotting_df['Simulation_Step'] = range(1, len(plotting_df) + 1)

plt.figure(figsize=(10, 6))
plt.plot(plotting_df['Simulation_Step'], plotting_df['battery_soc'], marker='o', label='Battery SOC')
plt.xlabel('Simulation Step')
plt.ylabel('State of Charge (SOC)')
plt.title('Battery State of Charge Over Time')
plt.ylim(0, 1) # SOC is typically between 0 and 1
plt.legend()
plt.grid(True)
plt.xticks(plotting_df['Simulation_Step'])
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Get the simulation history
history_data = microgrid.get_history()
history_df = pd.DataFrame(history_data)

# Filter out the initial state (first row where all power is 0) for plotting
plotting_df = history_df.iloc[1:].copy()

# Create a new column for simulation step numbers (1 to 5)
plotting_df['Simulation_Step'] = range(1, len(plotting_df) + 1)

plt.figure(figsize=(10, 6))
plt.plot(plotting_df['Simulation_Step'], plotting_df['battery_soc'], marker='o', label='Battery SOC')
plt.xlabel('Simulation Step')
plt.ylabel('State of Charge (SOC)')
plt.title('Battery State of Charge Over Time')
plt.ylim(0, 1) # SOC is typically between 0 and 1
plt.legend()
plt.grid(True)
plt.xticks(plotting_df['Simulation_Step'])
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Get the simulation history
history_data = microgrid.get_history()

# Convert the history to a pandas DataFrame
history_df = pd.DataFrame(history_data)

# Plot the net power balance over time
plt.figure(figsize=(10, 6))
plt.plot(history_df['time'], history_df['net_power_balance'], marker='o')
plt.xlabel('Time (h)')
plt.ylabel('Net Power Balance (kW)')
plt.title('Microgrid Net Power Balance Over Time')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Get the simulation history (assuming microgrid object is still defined)
history_data = microgrid.get_history()
history_df = pd.DataFrame(history_data)

# Retrieve component costs/prices from the microgrid object
diesel_gen = microgrid.components['diesel']
battery_comp = microgrid.components['battery']
grid_comp = microgrid.components['grid']

# Initialize cost/revenue columns
history_df['diesel_cost'] = 0.0
history_df['battery_cost'] = 0.0
history_df['grid_cost_revenue'] = 0.0

# Calculate costs/revenues for each timestep (assuming timestep=1 hour)
for i, row in history_df.iterrows():
    # Skip the initial state at time 0 (no power output/cost)
    if row['time'] == 0 and i == 0:
        continue

    # Diesel cost: Only when generating (power_output > 0)
    if row['diesel_power'] > 0:
        history_df.loc[i, 'diesel_cost'] = row['diesel_power'] * diesel_gen.generation_cost_per_kwh

    # Battery cost:
    # Discharge cost (power_output > 0 for discharge)
    if row['battery_power'] > 0:
        history_df.loc[i, 'battery_cost'] = row['battery_power'] * battery_comp.discharge_cost_per_kwh
    # Charge cost (power_output < 0 for charge)
    elif row['battery_power'] < 0:
        history_df.loc[i, 'battery_cost'] = abs(row['battery_power']) * battery_comp.charge_cost_per_kwh

    # Grid cost/revenue:
    # Import cost (power_output > 0 for import)
    if row['grid_power'] > 0:
        history_df.loc[i, 'grid_cost_revenue'] = row['grid_power'] * grid_comp.import_price_per_kwh
    # Export revenue (power_output < 0 for export, so revenue is negative cost)
    elif row['grid_power'] < 0:
        history_df.loc[i, 'grid_cost_revenue'] = row['grid_power'] * grid_comp.export_price_per_kwh # power_output is negative, export_price is positive, result is negative (revenue)

# Calculate total operational cost (sum of all costs/revenues)
history_df['total_operational_cost'] = history_df['diesel_cost'] + history_df['battery_cost'] + history_df['grid_cost_revenue']

# Set display option to show full float precision
pd.set_option('display.float_format', '{:.3f}'.format)

display(history_df)

# Reset display option to default after displaying if desired (optional)
# pd.reset_option('display.float_format')

import matplotlib.pyplot as plt

# Filter out the initial state (first row where all costs are 0) for plotting costs/revenues
# The first row of history_df corresponds to the initial state before any simulation step.
# The subsequent rows (starting from index 1) represent the results after each simulation step.
plotting_df = history_df.iloc[1:].copy()

# Create a new column for simulation step numbers (1 to 5)
plotting_df['Simulation_Step'] = range(1, len(plotting_df) + 1)

plt.figure(figsize=(14, 7))

# Plot individual costs/revenues using the new 'Simulation_Step' for x-axis
plt.plot(plotting_df['Simulation_Step'], plotting_df['diesel_cost'], label='Diesel Cost', marker='o')
plt.plot(plotting_df['Simulation_Step'], plotting_df['battery_cost'], label='Battery Operational Cost', marker='o')
plt.plot(plotting_df['Simulation_Step'], plotting_df['grid_cost_revenue'], label='Grid Cost/Revenue', marker='o')

# Plot total operational cost
plt.plot(plotting_df['Simulation_Step'], plotting_df['total_operational_cost'], label='Total Operational Cost/Revenue', color='black', linestyle='--', linewidth=2, marker='X')

plt.xlabel('Simulation Step')
plt.ylabel('Cost / Revenue ($)')
plt.title('Microgrid Component Costs and Revenues Over Time')
plt.axhline(0, color='gray', linestyle='-', linewidth=0.8) # Add a horizontal line at 0 for clarity
plt.legend()
plt.grid(True)
plt.xticks(plotting_df['Simulation_Step']) # Ensure all simulation steps are marked on x-axis
plt.tight_layout() # Adjust layout to prevent overlapping titles/labels
plt.show()

# Plot the power output of each component over time
import pandas as pd
import matplotlib.pyplot as plt

# Get the simulation history (assuming microgrid object is still defined)
history_data = microgrid.get_history()
history_df = pd.DataFrame(history_data)

# Filter out the initial state (first row where all power is 0) for plotting
plotting_df = history_df.iloc[1:].copy()

# Create a new column for simulation step numbers (1 to 5)
plotting_df['Simulation_Step'] = range(1, len(plotting_df) + 1)

plt.figure(figsize=(12, 8))

plt.plot(plotting_df['Simulation_Step'], plotting_df['wind_power'], marker='o', label='Wind Power')
plt.plot(plotting_df['Simulation_Step'], plotting_df['pv_power'], marker='o', label='PV Power')
plt.plot(plotting_df['Simulation_Step'], plotting_df['diesel_power'], marker='o', label='Diesel Power')
plt.plot(plotting_df['Simulation_Step'], plotting_df['battery_power'], marker='o', label='Battery Power')
plt.plot(plotting_df['Simulation_Step'], plotting_df['grid_power'], marker='o', label='Grid Power')
plt.plot(plotting_df['Simulation_Step'], plotting_df['load_power'], marker='o', label='Load Power (Consumption)')


plt.xlabel('Simulation Step')
plt.ylabel('Power (kW)')
plt.title('Microgrid Component Power Outputs Over Time')
plt.legend()
plt.grid(True)
plt.xticks(plotting_df['Simulation_Step']) # Ensure all simulation steps are marked on x-axis
plt.tight_layout() # Adjust layout to prevent overlapping titles/labels
plt.show()