# -*- coding: utf-8 -*-
"""Microgrid (No RL)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbi7lO6Jth6iVL2WTr9Lv75_nsiJ9ejn
"""



"""Let's define the components of your microgrid based on your input:

*   **Generation:** Wind turbine, PV (solar), Diesel generator, Energy storage (battery), Main grid connection.
*   **Customer Load:** Aggregate energy consumption of all customers.

Now, let's start creating simple models for each of these components. These models will define how each component interacts within the simulation.
"""

class MicrogridComponent:
    """Base class for all microgrid components."""
    def __init__(self, name):
        self.name = name
        self.power_output = 0  # Represents power output (positive) or consumption (negative)

    def update(self, timestep, data=None):
        """
        Update the component's state and power output based on the current timestep and data.
        This method should be implemented by subclasses.
        """
        raise NotImplementedError("Subclasses must implement the update method")

    def get_power_output(self):
        """Get the current power output of the component."""
        return self.power_output

    def __str__(self):
        return f"{self.name}: {self.power_output:.2f} kW"

"""Now, let's create classes for each of the specific microgrid components you've identified, inheriting from the `MicrogridComponent` base class. Each of these classes will need an `update` method that simulates its behavior over time."""

class WindTurbine(MicrogridComponent):
    """Represents a wind turbine."""
    def __init__(self, name, capacity):
        super().__init__(name)
        self.capacity = capacity  # Maximum power output in kW

    def update(self, timestep, data=None):
        """
        Update the wind turbine's power output based on wind speed data.

        Args:
            timestep: The current simulation timestep.
            data: A dictionary containing relevant data, e.g., {'wind_speed': float}.
        """
        if data and 'wind_speed' in data:
            wind_speed = data['wind_speed']
            # Simple wind power model (can be replaced with a more complex one)
            # Assuming a cut-in speed, rated speed, and cut-out speed
            cut_in_speed = 3  # m/s
            rated_speed = 12  # m/s
            cut_out_speed = 25  # m/s

            if wind_speed < cut_in_speed or wind_speed > cut_out_speed:
                self.power_output = 0
            elif wind_speed >= rated_speed:
                self.power_output = self.capacity
            else:
                # Linear interpolation between cut-in and rated speed
                self.power_output = self.capacity * (wind_speed - cut_in_speed) / (rated_speed - cut_in_speed)
        else:
            self.power_output = 0 # No wind data, no output

class PVSystem(MicrogridComponent):
    """Represents a PV (solar) system."""
    def __init__(self, name, capacity):
        super().__init__(name)
        self.capacity = capacity  # Maximum power output in kW

    def update(self, timestep, data=None):
        """
        Update the PV system's power output based on solar irradiance data.

        Args:
            timestep: The current simulation timestep.
            data: A dictionary containing relevant data, e.g., {'solar_irradiance': float}.
        """
        if data and 'solar_irradiance' in data:
            solar_irradiance = data['solar_irradiance'] # Assuming data is in W/m^2
            # Simple PV power model (can be replaced with a more complex one)
            # Assuming a standard test condition (STC) irradiance of 1000 W/m^2
            stc_irradiance = 1000
            self.power_output = self.capacity * (solar_irradiance / stc_irradiance)
            # Ensure output does not exceed capacity
            if self.power_output > self.capacity:
                self.power_output = self.capacity
            # Ensure output is not negative
            if self.power_output < 0:
                self.power_output = 0
        else:
            self.power_output = 0 # No solar data, no output

class DieselGenerator(MicrogridComponent):
    """Represents a diesel generator."""
    def __init__(self, name, capacity, fuel_consumption_rate=0.2):
        super().__init__(name)
        self.capacity = capacity  # Maximum power output in kW
        self.fuel_consumption_rate = fuel_consumption_rate # Example: fuel consumed per kWh generated
        self.fuel_level = 1000 # Example: initial fuel level
        self.is_running = False

    def update(self, timestep, data=None):
        """
        Update the diesel generator's power output and fuel level.

        Args:
            timestep: The current simulation timestep.
            data: A dictionary containing relevant data, e.g., {'required_power': float}.
                  This could also include commands to start/stop the generator.
        """
        # Simple model: Generator runs to meet a power requirement if needed and fuel is available
        required_power = data.get('required_power', 0) if data else 0

        if required_power > 0 and self.fuel_level > 0:
            self.is_running = True
            # Generate power up to capacity or required power, whichever is less
            self.power_output = min(self.capacity, required_power)
            # Calculate fuel consumption based on generated power and rate
            # Assuming timestep is in hours for fuel calculation
            fuel_consumed = self.power_output * self.fuel_consumption_rate * timestep
            self.fuel_level -= fuel_consumed
            if self.fuel_level < 0:
                self.fuel_level = 0
                self.is_running = False # Stop if fuel runs out
                self.power_output = 0
        else:
            self.is_running = False
            self.power_output = 0

    def get_fuel_level(self):
        """Get the current fuel level."""
        return self.fuel_level

    def __str__(self):
        return f"{self.name}: {self.power_output:.2f} kW, Fuel: {self.fuel_level:.2f}"

"""Now that we have models for each component, let's integrate them into a main `Microgrid` simulation environment. This class will manage all the components and simulate their interactions over time."""

class Battery(MicrogridComponent):
    """Represents an energy storage system (battery)."""
    def __init__(self, name, capacity_kwh, max_charge_rate_kw, max_discharge_rate_kw, initial_soc=0.5):
        super().__init__(name)
        self.capacity_kwh = capacity_kwh  # Total energy capacity in kWh
        self.max_charge_rate_kw = max_charge_rate_kw  # Maximum charging power in kW
        self.max_discharge_rate_kw = max_discharge_rate_kw  # Maximum discharging power in kW
        self.soc = initial_soc  # State of Charge (0.0 to 1.0)
        self.power_output = 0 # Power output (discharge is positive, charge is negative)

    def update(self, timestep, data=None):
        """
        Update the battery's state of charge and power output.

        Args:
            timestep: The current simulation timestep (in hours).
            data: A dictionary containing relevant data, e.g., {'charge_power': float} or {'discharge_power': float}.
                  Positive values for discharge, negative for charge.
        """
        if data and ('charge_power' in data or 'discharge_power' in data):
            requested_power = data.get('discharge_power', 0) - data.get('charge_power', 0) # Positive for discharge, negative for charge

            # Limit requested power by max charge/discharge rates
            if requested_power > self.max_discharge_rate_kw:
                requested_power = self.max_discharge_rate_kw
            elif requested_power < -self.max_charge_rate_kw:
                requested_power = -self.max_charge_rate_kw

            # Calculate potential change in SOC
            energy_change_kwh = requested_power * timestep
            potential_new_soc = self.soc + (energy_change_kwh / self.capacity_kwh)

            # Limit SOC between 0 and 1
            if potential_new_soc > 1.0:
                actual_energy_change_kwh = (1.0 - self.soc) * self.capacity_kwh
                self.soc = 1.0
                self.power_output = actual_energy_change_kwh / timestep # Actual discharge power
            elif potential_new_soc < 0.0:
                actual_energy_change_kwh = (0.0 - self.soc) * self.capacity_kwh
                self.soc = 0.0
                self.power_output = actual_energy_change_kwh / timestep # Actual charge power (will be negative)
            else:
                self.soc = potential_new_soc
                self.power_output = requested_power # Actual power is the same as requested

        else:
            self.power_output = 0 # No charge/discharge command
            # SOC remains the same if no power is requested

    def get_soc(self):
        """Get the current state of charge (SOC)."""
        return self.soc

    def __str__(self):
        return f"{self.name}: {self.power_output:.2f} kW, SOC: {self.soc:.2f}"

class MainGrid(MicrogridComponent):
    """Represents the connection to the external power grid."""
    def __init__(self, name, import_limit=float('inf'), export_limit=float('inf')):
        super().__init__(name)
        self.import_limit = import_limit  # Maximum power that can be imported from the grid (kW)
        self.export_limit = export_limit  # Maximum power that can be exported to the grid (kW)
        self.power_output = 0  # Power flow (positive for import, negative for export)

    def update(self, timestep, data=None):
        """
        Update the main grid's power flow.

        Args:
            timestep: The current simulation timestep.
            data: A dictionary containing relevant data, e.g., {'requested_power': float}.
                  Positive values for importing from the grid, negative for exporting.
        """
        requested_power = data.get('requested_power', 0) if data else 0

        if requested_power > 0:  # Requesting power from the grid (import)
            self.power_output = min(requested_power, self.import_limit)
        elif requested_power < 0:  # Sending power to the grid (export)
            self.power_output = max(requested_power, -self.export_limit) # export_limit is positive, so we need the negative
        else:
            self.power_output = 0 # No power exchange requested

    def __str__(self):
        # Display positive for import, negative for export
        flow_direction = "importing" if self.power_output > 0 else ("exporting" if self.power_output < 0 else "not exchanging")
        return f"{self.name}: {abs(self.power_output):.2f} kW ({flow_direction})"

class CustomerLoad(MicrogridComponent):
    """Represents the aggregate energy consumption of customers."""
    def __init__(self, name):
        super().__init__(name)
        self.power_output = 0  # Load is power consumption (negative in our convention)

    def update(self, timestep, data=None):
        """
        Update the customer load based on load data.

        Args:
            timestep: The current simulation timestep.
            data: A dictionary containing relevant data, e.g., {'load': float}.
                  Load should be a positive value representing consumption.
        """
        if data and 'load' in data:
            # Load is consumption, so it's negative power output
            self.power_output = -data['load']
        else:
            self.power_output = 0 # No load data, no consumption

    def __str__(self):
        # Display load as a positive value
        return f"{self.name}: {abs(self.power_output):.2f} kW (consumption)"

class Microgrid:
    """Represents the microgrid simulation environment."""
    def __init__(self, components):
        """
        Args:
            components: A dictionary of MicrogridComponent objects, e.g., {'wind': WindTurbine(...), 'battery': Battery(...), ...}.
        """
        self.components = components
        self.time = 0
        self.history = [] # To store simulation results

    def update(self, timestep, data):
        """
        Update the state of all components for the current timestep and manage power balance.

        Args:
            timestep: The duration of the current timestep (in hours).
            data: A dictionary containing data for each component, e.g., {'wind': {'wind_speed': ...}, 'customer_load': {'load': ...}}.
        """
        current_state = {'time': self.time}
        total_generation = 0
        total_load = 0

        # Update renewable sources and load first
        for name, component in self.components.items():
            component_data = data.get(name, {})
            if name in ['wind', 'pv']: # Renewable sources
                 component.update(timestep, component_data)
                 current_state[name + '_power'] = component.get_power_output()
                 total_generation += component.get_power_output()
            elif name == 'load': # Load
                 component.update(timestep, component_data)
                 current_state[name + '_power'] = component.get_power_output()
                 total_load += component.get_power_output() # load_power is negative, so adding it increases the deficit

        net_power_balance = total_generation + total_load # Positive means surplus, negative means deficit

        # Simple dispatch logic to manage net power balance
        power_to_balance = -net_power_balance # Power needed if deficit (positive), power to absorb if surplus (negative)

        # Prioritize discharging battery for deficit
        battery = self.components.get('battery')
        if battery and power_to_balance > 0:
             battery.update(timestep, {'discharge_power': power_to_balance})
             power_to_balance -= battery.get_power_output()
             current_state['battery_power'] = battery.get_power_output() # Update state with actual power

        # Use grid for remaining deficit
        grid = self.components.get('grid')
        if grid and power_to_balance > 0:
             grid.update(timestep, {'requested_power': power_to_balance}) # Request import
             power_to_balance -= grid.get_power_output()
             current_state['grid_power'] = grid.get_power_output() # Update state with actual power

        # Use diesel generator for any remaining deficit
        diesel = self.components.get('diesel')
        if diesel and power_to_balance > 0:
             diesel.update(timestep, {'required_power': power_to_balance})
             power_to_balance -= diesel.get_power_output()
             current_state['diesel_power'] = diesel.get_power_output() # Update state with actual power


        # Prioritize charging battery for surplus
        if battery and power_to_balance < 0:
             battery.update(timestep, {'charge_power': -power_to_balance}) # Request charge (charge_power is positive in update)
             power_to_balance += (-battery.get_power_output()) # Add the negative power output (charge) back
             current_state['battery_power'] = battery.get_power_output() # Update state with actual power

        # Export to grid for remaining surplus
        if grid and power_to_balance < 0:
             grid.update(timestep, {'requested_power': power_to_balance}) # Request export (negative)
             power_to_balance += (-grid.get_power_output()) # Add the negative power output (export) back
             current_state['grid_power'] = grid.get_power_output() # Update state with actual power

        # Ensure all components that weren't explicitly dispatched have their power_output recorded
        for name, component in self.components.items():
             if name not in current_state:
                  current_state[name + '_power'] = component.get_power_output()


        # The remaining power_to_balance should ideally be close to zero if all demand is met or surplus absorbed
        # We can store the final net balance after dispatch
        current_state['net_power_balance'] = total_generation + total_load + \
                                             current_state.get('battery_power', 0) + \
                                             current_state.get('grid_power', 0) + \
                                             current_state.get('diesel_power', 0)


        # Store the current state
        self.history.append(current_state)

        # Advance time
        self.time += timestep

    def run_simulation(self, timesteps, data_series):
        """
        Run the microgrid simulation for a specified number of timesteps.

        Args:
            timesteps: The total number of timesteps to simulate.
            data_series: A list of dictionaries, where each dictionary contains the data for a single timestep.
                         The length of this list should be equal to the number of timesteps.
        """
        if len(data_series) != timesteps:
            raise ValueError("Length of data_series must match the number of timesteps.")

        self.history = [] # Reset history for a new simulation run
        self.time = 0 # Reset time

        # Initialize component states at time 0 before the first update
        initial_state = {'time': self.time}
        for name, component in self.components.items():
             initial_state[name + '_power'] = component.get_power_output() # Should be 0 initially for most
        initial_state['net_power_balance'] = 0 # Assuming initial state is balanced
        self.history.append(initial_state)


        for i in range(timesteps):
            timestep_data = data_series[i]
            # Assuming each step represents 1 hour for now
            self.update(1, timestep_data)
            print(f"Time: {self.time}h, Net Balance (after dispatch): {self.history[-1]['net_power_balance']:.2f} kW")
            # Optional: Print component states
            # for name, component in self.components.items():
            #     print(f"  {component}")


    def get_history(self):
        """Get the simulation history."""
        return self.history

    def __str__(self):
        return f"Microgrid with components: {', '.join(self.components.keys())}"

"""Now that we have the microgrid simulation environment, we need to define the **state space** and **action space** for reinforcement learning.

*   **State Space:** What information about the microgrid is available to the reinforcement learning agent at each timestep? This could include things like:
    *   Current power output of each generation source (wind, solar, diesel)
    *   Battery state of charge (SOC)
    *   Customer load
    *   Time of day/year (can influence renewable generation and load)
    *   Grid status/price (if connected to the main grid)

*   **Action Space:** What decisions can the reinforcement learning agent make at each timestep? This could include:
    *   Dispatching the diesel generator (on/off, power output level)
    *   Charging or discharging the battery (power level)
    *   Buying or selling power to the main grid (power level)

Let's think about what a suitable state and action space would be for your microgrid setup. We can start by defining these spaces based on the components you have included.
"""

# Create instances of the microgrid components
wind_turbine = WindTurbine(name='WindTurbine', capacity=100)
pv_system = PVSystem(name='PVSystem', capacity=50)
diesel_generator = DieselGenerator(name='DieselGenerator', capacity=75)
battery = Battery(name='Battery', capacity_kwh=200, max_charge_rate_kw=50, max_discharge_rate_kw=50)
main_grid = MainGrid(name='MainGrid', import_limit=100, export_limit=100)
customer_load = CustomerLoad(name='CustomerLoad')

# Create a Microgrid instance with the components
components = {
    'wind': wind_turbine,
    'pv': pv_system,
    'diesel': diesel_generator,
    'battery': battery,
    'grid': main_grid,
    'load': customer_load
}
microgrid = Microgrid(components)

# Create some sample time-series data for a few timesteps
# This data would typically come from external sources or profiles
sample_data_series = [
    {'wind': {'wind_speed': 8}, 'pv': {'solar_irradiance': 700}, 'load': {'load': 60}}, # Timestep 1: Wind and solar generating, some load (surplus)
    {'wind': {'wind_speed': 5}, 'pv': {'solar_irradiance': 100}, 'load': {'load': 150}}, # Timestep 2: Low wind and solar, high load (deficit - might need diesel/grid/battery discharge)
    {'wind': {'wind_speed': 2}, 'pv': {'solar_irradiance': 900}, 'load': {'load': 80}},  # Timestep 3: Low wind, high solar, lower load (surplus - might charge battery/export)
    {'wind': {'wind_speed': 10}, 'pv': {'solar_irradiance': 0}, 'load': {'load': 120}}, # Timestep 4: Wind generating, no solar (night), high load (deficit - might need diesel/grid/battery discharge)
    {'wind': {'wind_speed': 7}, 'pv': {'solar_irradiance': 500}, 'load': {'load': 50}},  # Timestep 5: Moderate wind and solar, low load (surplus - might charge battery/export)
]

# Run the simulation
timesteps_to_simulate = len(sample_data_series)
microgrid.run_simulation(timesteps_to_simulate, sample_data_series)

# Display the simulation history
display(microgrid.get_history())

import pandas as pd
import matplotlib.pyplot as plt

# Get the simulation history
history_data = microgrid.get_history()

# Convert the history to a pandas DataFrame
history_df = pd.DataFrame(history_data)

# Plot the net power balance over time
plt.figure(figsize=(10, 6))
plt.plot(history_df['time'], history_df['net_power_balance'], marker='o')
plt.xlabel('Time (h)')
plt.ylabel('Net Power Balance (kW)')
plt.title('Microgrid Net Power Balance Over Time')
plt.grid(True)
plt.show()

# Plot the power output of each component over time
plt.figure(figsize=(12, 8))

plt.plot(history_df['time'], history_df['wind_power'], marker='o', label='Wind Power')
plt.plot(history_df['time'], history_df['pv_power'], marker='o', label='PV Power')
plt.plot(history_df['time'], history_df['diesel_power'], marker='o', label='Diesel Power')
plt.plot(history_df['time'], history_df['battery_power'], marker='o', label='Battery Power')
plt.plot(history_df['time'], history_df['grid_power'], marker='o', label='Grid Power')
plt.plot(history_df['time'], history_df['load_power'], marker='o', label='Load Power (Consumption)')


plt.xlabel('Time (h)')
plt.ylabel('Power (kW)')
plt.title('Microgrid Component Power Outputs Over Time')
plt.legend()
plt.grid(True)
plt.show()